services:
  app:
    container_name: app
    build: .
    command:
      [
        'dockerize',
        '-wait',
        'tcp://db:3306',
        '-timeout',
        '20s',
        'node',
        'dist/main.js',
      ]
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dddatabase
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
